# Working with Matrices

### Back to our domain

|ad spending    |sales spending    | 
| :-------------:|:-------------:|
|    200        |800        |
|    500        |600        |
|    1000      | 700      | 
|    2000      | 300      | 
|    3000      | 100      | 

$a_1 = \begin{pmatrix}
    200 \\
    500 \\
    1000 \\
    2000 \\
    3000 \\
\end{pmatrix}, a_2 = \begin{pmatrix}
    800 \\
    600 \\
    700 \\
    300 \\
    100\\
\end{pmatrix}$

$ A = \begin{pmatrix}
    200 & 800 \\
    500 & 600\\
    1000 & 700\\
    2000 & 300\\
    3000 & 100\\
\end{pmatrix}$

### Introduction to matrices

> A **matrix** is a rectangular array  of values, arranged in rows and columns.

To describe matrices in general we say that:
* $A \in \mathbb{R}^{mxn}$ where $m$ is the number of rows of the matrix and $n$ is the number of columns.

### Specifying entries of a matrix

$ 
C = \left[\begin{array}{cccc} 
C_{11} & C_{12} & \cdots & C_{1n} \\ 
C_{21} & C_{22} & \cdots & C_{2n} \\ 
\vdots & \vdots & \ddots & \vdots \\ 
C_{m1} & C_{m2} & \cdots & C_{mn}
\end{array} \right ] $ 

Let's go back to our original matrix $A$ and specify some of the entries.

$A =  \begin{pmatrix}
800 & 13  \\
1500 & 11 \\
2000 & 9 \\
3500 & 10 \\
4000 & 8 \\
\end{pmatrix}$ 

To describe the entire matrix, A, we would say $A \in \mathbb{R}^{5x2}.$ 

### Transpose of a matrix

In [2]:
import numpy as np
A = np.array([
    [200, 800],
    [500, 600],
    [1000, 700],
    [2000, 300],
    [3000, 100],
                 ])
A

array([[ 200,  800],
       [ 500,  600],
       [1000,  700],
       [2000,  300],
       [3000,  100]])

Beyond selecting the rows and columns of a matrix, we can also switch the rows and columns.  For example, above we have the matrix $A$, that has five rows and two columns.

In [6]:
A

array([[ 200,  800],
       [ 500,  600],
       [1000,  700],
       [2000,  300],
       [3000,  100]])

In [8]:
A.T

array([[ 200,  500, 1000, 2000, 3000],
       [ 800,  600,  700,  300,  100]])