# Different Multiplication Views

### Vector Vector Multiplication revisited

In [4]:
import numpy as np
A = np.array([[25, 8],
              [5, 6],
              [10, 7]
             ])
X = np.array([[1, 2, 4],
              [3, 4, 5]])

In [5]:
a_1, x_1 = A[:1, :2], X[:2, :1]
a_1, x_1

(array([[25,  8]]),
 array([[1],
        [3]]))

In [17]:
a_1.shape, x_1.shape

((1, 2), (2, 1))

In [6]:
a_1.dot(x_1)

array([[49]])

In [20]:
x_1, a_1

(array([[1],
        [3]]),
 array([[25,  8]]))

In [21]:
x_1.shape, a_1.shape

((2, 1), (1, 2))

In [22]:
x_1.dot(a_1)

array([[25,  8],
       [75, 24]])

$a_1 \cdot x_1^T  = \begin{pmatrix}
    1  \\
    3 \\
\end{pmatrix}  \cdot \begin{pmatrix}
25 & 8
\end{pmatrix} = \left[ 25 \begin{pmatrix}
1 \\
3
\end{pmatrix} 8 \begin{pmatrix}
1 \\
3
\end{pmatrix} \right]= \begin{pmatrix}
25 & 8 \\ 
75 & 24 
\end{pmatrix}$
    


### Matrix Matrix Multiplication revisited

In [7]:
import numpy as np
A = np.array([[25, 8],
              [5, 6],
              [10, 7]
             ])
X = np.array([[1, 2, 4],
              [3, 4, 5]])

$A \cdot X  =  \begin{pmatrix}
    25 & 8 \\
    5 & 6\\
    10 & 7\\
\end{pmatrix} \cdot \begin{pmatrix}
    1 & 2 & 4\\ 3 & 4 & 5 
\end{pmatrix}  = \begin{pmatrix}
    25  \\
    5 \\
    10\\
\end{pmatrix} \cdot \begin{pmatrix}
    1 & 2 & 4 
\end{pmatrix}  + \begin{pmatrix}
    8  \\
    6 \\
    7\\
\end{pmatrix} \cdot \begin{pmatrix}
    3 & 4 & 5 
\end{pmatrix}$

And remember, that each column by row dot product results in separate *matrix*.

In [27]:
A[:4, :1].dot(X[:1, :4]), A[:4, 1:2].dot(X[1:2, :4]) 

(array([[ 25,  50, 100],
        [  5,  10,  20],
        [ 10,  20,  40]]),
 array([[24, 32, 40],
        [18, 24, 30],
        [21, 28, 35]]))

$A \cdot X  = \begin{pmatrix}
    25 & 50 & 100 \\  5 &  10 &  20 \\ 10 &  20 & 40
\end{pmatrix}  + \begin{pmatrix}
    24 & 32 & 40 \\  18 &  24 &  30 \\ 21 &  28 & 35
\end{pmatrix} =  \begin{pmatrix}
    49 & 82 & 140 \\  23 &  34 &  50 \\ 31 &  48 & 75
\end{pmatrix}$

In [28]:
A[:4, :1].dot(X[:1, :4]) +  A[:4, 1:2].dot(X[1:2, :4]) 

array([[ 49,  82, 140],
       [ 23,  34,  50],
       [ 31,  48,  75]])

### Summary

$A \cdot X  =  \begin{pmatrix}
    25 & 8 \\
    5 & 6\\
    10 & 7\\
\end{pmatrix} \cdot \begin{pmatrix}
    1 & 2 & 4\\ 3 & 4 & 5 
\end{pmatrix} = \begin{pmatrix}
    25  \\
    5 \\
    10\\
\end{pmatrix} \cdot \begin{pmatrix}
    1 & 2 & 4 
\end{pmatrix}  + \begin{pmatrix}
    8  \\
    6 \\
    7\\
\end{pmatrix} \cdot \begin{pmatrix}
    3 & 4 & 5 
\end{pmatrix} = $ 


$\begin{pmatrix}
    25 & 50 & 100 \\  5 &  10 &  20 \\ 10 &  20 & 40
\end{pmatrix}  + \begin{pmatrix}
    24 & 32 & 40 \\  18 &  24 &  30 \\ 21 &  28 & 35
\end{pmatrix} =  \begin{pmatrix}
    49 & 82 & 140 \\  23 &  34 &  50 \\ 31 &  48 & 75
\end{pmatrix}$

$A_{: 1} \cdot X_{1 :}  =  \begin{pmatrix}
    25  \\
    5 \\
    10 \\
\end{pmatrix} \cdot \begin{pmatrix}
    1 & 2 & 4
\end{pmatrix} = \begin{pmatrix}
    25 & 50 & 100 \\  5 &  10 &  20 \\ 10 &  20 & 40
\end{pmatrix}$

And then add in the second layer, through the second dot product.

$A_{: 2} \cdot X_{2 :}  =  \begin{pmatrix}
    8  \\
    6 \\
    7 \\
\end{pmatrix} \cdot \begin{pmatrix}
    3 & 4 & 5
\end{pmatrix} = \begin{pmatrix}
    24 & 32 & 40 \\  18 &  24 &  30 \\ 21 &  28 & 35
\end{pmatrix}$

### Summary

In this lesson, we began by reviewing the result of dotting a row by a column and moved onto dotting a column by a row.  We saw that while our standard dot product $a^T \cdot b$ results in a scalar number:

$a \cdot b^T  = \begin{pmatrix}
a_1 & a_2
\end{pmatrix} \cdot \begin{pmatrix}
    b_1  \\
    b_2 \\
\end{pmatrix}   = c$

Dotting a column by a row results in a matrix:

$a \cdot b^T  = \begin{pmatrix}
    a_1  \\
    a_2 \\
\end{pmatrix}  \cdot \begin{pmatrix}
b_1 & b_2
\end{pmatrix} = \left[ b_1 \begin{pmatrix}
a_1 \\
a_2
\end{pmatrix} b_2 \begin{pmatrix}
a_1 \\
a_2
\end{pmatrix} \right]= \begin{pmatrix}
a_1b_1 & a_1b_2 \\ 
a_2b_1 & a_2b_2 
\end{pmatrix}$
    
