### Solving systems of linear equations

Lecture 6, minute 45

So can multiply 

$Ax  = b$

In [18]:
import numpy as np
A = np.array([[4, -5],
          [-2, 3],
          [-2, 3]
         ])

b = [-13, 9, 9]

In [16]:
# np.linalg.inv(A)

In [13]:
A @ inverse

array([-13.,   9.,   9.])

So if we give you a system of linear equations, we can get the solution back.

In [20]:
np.linalg.lstsq(A, b)

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  """Entry point for launching an IPython kernel.


(array([3., 5.]), array([8.05143442e-32]), 2, array([8.17804276, 0.34585624]))

In [21]:
A @ np.array([3, 5])

array([-13,   9,   9])

### Extras

* Miscellaneous definitions , 37:59
* Inner product 
    * For hypothesis function
* Vector Norms - L2 norm vs l1 norm