# Matrix Operations and Matrix Dimensions

### Introduction

Now that we have learned the main operations that we can perform with vectors and matrices, we should cover explicitly some of the rules for working with each.  In short, there are certain operations that simply don't make sense or work in linear algebra.

### The rules for addition

For addition, the rules are pretty simple.  We can only add two vectors or two matrices together if they have the same dimensions.  Let's see this.

* Add matrices

In [3]:
import numpy as np
A = np.array([
    [200, 800],
    [500, 600],
    [1000, 700],
    [2000, 300],
    [3000, 100],
                 ])

Note that given our above rules, we can add a matrix by itself.

In [4]:
A + A

array([[ 400, 1600],
       [1000, 1200],
       [2000, 1400],
       [4000,  600],
       [6000,  200]])

However, we cannot add a matrix of a different size.  Let's assign a Matrix B, to be all but the first row of matrix A.

In [7]:
B = A[1:]
B

array([[ 500,  600],
       [1000,  700],
       [2000,  300],
       [3000,  100]])

In [8]:
A + B

ValueError: operands could not be broadcast together with shapes (5,2) (4,2) 

So as we can see by the error message, that becase the matrices have different sheapes, we cannot add them.

In [9]:
A.shape

(5, 2)

In [10]:
B.shape

(4, 2)

* Adding Vectors

Vector addition comes with the same constraint.  Two vectors must be of the same shape for us to add them.

In [11]:
a = np.array([1200, 300, -400, 600, 200])

c = np.array([200, 300, 700, 4000])

In [12]:
a + c

ValueError: operands could not be broadcast together with shapes (5,) (4,) 

## Matrix Matrix multiplication

In multiplying two matrices together (or multiplying a vector and matrix together), we have the following rule:

> The number of columns of the first matrix must match the number of rows of the second matrix.

This makes sense, from the procedure of matrix vector multiplication that we saw previously.

$ A \cdot x =  \begin{pmatrix}
    200 & 800 \\
    500 & 600\\
    1000 & 700\\
    2000 & 300\\
    3000 & 100\\
\end{pmatrix} \cdot \begin{pmatrix}
    .35 \\ .6 
\end{pmatrix} = .35* \begin{pmatrix}
    200  \\
    500  \\
    1000 \\
    2000 \\ 
    3000 \\ 
\end{pmatrix} + .6* \begin{pmatrix}
     800 \\
     600 \\
     700 \\
     300 \\ 
     100 \\ 
\end{pmatrix} $


Our process is to split the first matrix into separate columns, and then multiply each column by the multiplying vector.  If the number of rows in the multiplying vector don't match the number of our columns in the first matrix, we won't be able to align the two.

There's a rule that is often taught for matrix matrix multiplication:

Given two matrices with dimensions $A^{mxn} \cdot B^{qxp}$, the inner dimensions must be equal.

So above, we can only multiply A and B if n = q, that is if the number of columns in our first matrix equals the number of rows in our second.  Let's see this:

In [15]:
A.shape

(5, 2)

In [17]:
B.shape

(4, 2)

If we multiply A by B, we should receive an error, as the inner dimensions do not equal.  The number of columns of A is 2, while the number of rows in B is 4.

> We can use the `@` symbol to apply any linear algebra multiplication in numpy.

In [18]:
A @ B

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 4 is different from 2)

In [28]:
C = np.ones((4, 2))
C

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [29]:
D = B[2:]
D

array([[2000,  300],
       [3000,  100]])

Now let's try multiplying $D \cdot C $.  

* First let's have a guess as to whether we can do so.

In [32]:
D @ C

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 4 is different from 2)

If we multiply D by C, we get an error, as the number of columns in our first matrix is two while the number of rows in our second matrix, C, is 4.  However if we try the refverse, this works:

In [33]:
C @ D

array([[5000.,  400.],
       [5000.,  400.],
       [5000.,  400.],
       [5000.,  400.]])

One final take away.  When we multiply two matrices together $A^{mxn} \cdot C^{pxq}$, the resulting matrix will be of shape $(m, q)$.  Notice that when we multiplied C by D, this is what we saw.

In [34]:
C.shape

(4, 2)

In [35]:
D.shape

(2, 2)

In [36]:
(C @ D).shape

(4, 2)

In [37]:
C @ D

array([[5000.,  400.],
       [5000.,  400.],
       [5000.,  400.],
       [5000.,  400.]])

Understanding how matrix matrix multiplication occurs is something that we did not cover.  For now, you can simply use numpy to perform the calculation.  The bigger point is an understanding of whether one can perform matrix matrix multiplication, and the resulting dimensions of the composite matrix.

### Summary

In this lesson, we learned that whether or not certain operations can be performed depend on the dimensions of the matrices or vectors we are working with.

* To add two vectors or two matrices together, they must have the same shape.
* In multiplying two matrices together or a matrix and a vector, the number columns of the first matrix must equal the number of rows of the second matrix
* In multiplying two matrices or a matrix and a vector together the dimensions of the resulting matrix will be the rows of the first matrix and the columns of the second. 