# Vector Addition and Scaling Lab

### Introduction

In [12]:
import pandas as pd
url = "https://raw.githubusercontent.com/jigsawlabs-student/linear-algebra/master/2-matrices/1-data-vectors/beer.csv"

results_df = pd.read_csv(url, index_col = 0)

Let's start by taking a look at the columns.

In [13]:
results_df[:2]

taxpayer_number           taxpayer_name    taxpayer_address taxpayer_city  \
0      17429444858  CHIPOTLE TEXAS, L.L.C.  445 N HIGH ST FL 3      COLUMBUS   
1      17429444858  CHIPOTLE TEXAS, L.L.C.  445 N HIGH ST FL 3      COLUMBUS   

  taxpayer_state  taxpayer_zip  taxpayer_county  location_number  \
0             OH         43215                0              104   
1             OH         43215                0              104   

            location_name           location_address  ... location_county  \
0  CHIPOTLE MEXICAN GRILL  2411 GLENNA GOODACRE BLVD  ...             152   
1  CHIPOTLE MEXICAN GRILL  2411 GLENNA GOODACRE BLVD  ...             152   

  inside_outside_city_limits_code_y_n  tabc_permit_number  \
0                                   Y            MB762148   
1                                   Y            MB762148   

   responsibility_begin_date_yyyymmdd obligation_end_date_yyyymmdd  \
0             2010-11-19T00:00:00.000      2020-05-31T00:00:00.000   
1             2010-11-19T00:00:00.000      2020-04-30T00:00:00.000   

  liquor_receipts wine_receipts beer_receipts  cover_charge_receipts  \
0               0             0             8                      0   
1               0             0             0                      0   

   total_receipts  
0               8  
1               0  

[2 rows x 23 columns]

Ok, now let's just select `beer_receipts`, `liquor_receipts` and `total_receipts` columns from the dataframe above.  Convert each of the columns to be numeric.

In [15]:
beer_and_liquor_df = None

In [16]:
beer_and_liquor_df[:2]

# beer_receipts	liquor_receipts	total_receipts
# 0	8	0	8
# 1	0	0	0

beer_receipts  liquor_receipts  total_receipts
0              8                0               8
1              0                0               0

In [17]:
beer_and_liquor_df.dtypes

# beer_receipts      int64
# liquor_receipts    int64
# total_receipts     int64
# dtype: object

beer_receipts      int64
liquor_receipts    int64
total_receipts     int64
dtype: object

Ok now let's assign the variables `beer_receipts` and `liquor_receipts` as numpy arrays.

In [18]:
beer_receipts = None

In [19]:
beer_receipts

# array([  8,   0,  46,  99, 110,  71, 128, 182, 114, 133, 148, 538, 650,
#        381, 367, 153, 497, 308, 187, 517, 394, 455, 381, 162,  97, 442,
#        409, 429, 251,  92,   0,  93, 530, 208, 103, 559, 119, 158, 615,
#        342, 135, 527, 297, 211, 187, 387, 194, 590, 535, 115, 378,  88,
#        394, 204, 165, 378, 160, 208, 410, 244, 310, 158, 147, 129, 584,
#        187, 337, 777, 266, 516, 205, 160, 498, 128, 235, 434, 218, 323,
#        398, 249, 196, 460, 142, 407, 515,   0, 278, 385, 396, 149, 313,
#        143, 114, 508, 472, 346, 292, 115, 149, 251, 256, 175, 527,   0,
#        354,  86, 643, 171, 135, 438, 185, 115, 267, 504, 315])

array([  8,   0,  46,  99, 110,  71, 128, 182, 114, 133, 148, 538, 650,
       381, 367, 153, 497, 308, 187, 517, 394, 455, 381, 162,  97, 442,
       409, 429, 251,  92,   0,  93, 530, 208, 103, 559, 119, 158, 615,
       342, 135, 527, 297, 211, 187, 387, 194, 590, 535, 115, 378,  88,
       394, 204, 165, 378, 160, 208, 410, 244, 310, 158, 147, 129, 584,
       187, 337, 777, 266, 516, 205, 160, 498, 128, 235, 434, 218, 323,
       398, 249, 196, 460, 142, 407, 515,   0, 278, 385, 396, 149, 313,
       143, 114, 508, 472, 346, 292, 115, 149, 251, 256, 175, 527,   0,
       354,  86, 643, 171, 135, 438, 185, 115, 267, 504, 315])

In [20]:
liquor_receipts = None

In [21]:
liquor_receipts

# array([  0,   0,  55,  52,  52,  57, 133,  26,  40, 104, 144, 327, 340,
#        486, 383, 116, 180, 144, 172, 935, 662, 185, 602, 147,  78, 787,
#        560, 682, 161, 151,   0,  59, 288, 147,  69, 275, 132, 116, 315,
#        531,  54, 234, 334,  78, 161, 149,  76, 815, 302,  76, 357, 121,
#        185,  95, 329, 631, 139, 204, 319, 178, 144,  78, 128, 183, 342,
#        249, 167, 514, 349, 319, 380, 163, 937, 118, 251, 252, 168, 189,
#        445, 280, 241, 189,  75, 761, 615,   0,  27, 482, 488, 159, 656,
#        111,  76, 248, 167,  81, 334, 137, 114, 297, 213, 175, 252,   0,
#        480, 133, 302, 149, 102, 409, 185,  31, 166, 261, 595])

array([  0,   0,  55,  52,  52,  57, 133,  26,  40, 104, 144, 327, 340,
       486, 383, 116, 180, 144, 172, 935, 662, 185, 602, 147,  78, 787,
       560, 682, 161, 151,   0,  59, 288, 147,  69, 275, 132, 116, 315,
       531,  54, 234, 334,  78, 161, 149,  76, 815, 302,  76, 357, 121,
       185,  95, 329, 631, 139, 204, 319, 178, 144,  78, 128, 183, 342,
       249, 167, 514, 349, 319, 380, 163, 937, 118, 251, 252, 168, 189,
       445, 280, 241, 189,  75, 761, 615,   0,  27, 482, 488, 159, 656,
       111,  76, 248, 167,  81, 334, 137, 114, 297, 213, 175, 252,   0,
       480, 133, 302, 149, 102, 409, 185,  31, 166, 261, 595])

We should do the same with `total_receipts`.

In [22]:
total_reciepts = None

### Working with Vectors in Numpy

First, let's use our knowledge of numpy and vectors to select specific data.  Start by selecting the first three entries for liquor receipts.

In [23]:
selected_liquor = None
selected_liquor
# array([ 0,  0, 55])

array([ 0,  0, 55])

Select the first three entries for beer reciepts.

In [25]:
selected_beer = None
selected_beer
# array([ 8,  0, 46])


array([ 8,  0, 46])

### Adding Vectors

We would like to add up the beer and liquor receipts for this chipotle location.  Calculate the combined receipts for the first three entries of liquor and beer.

In [26]:
combined_receipts = None
combined_receipts
# array([  8,   0, 101])

array([  8,   0, 101])

We can confirm that it this combination also equals the total receipts for the first three entries.

In [27]:
total_reciepts[:3]

array([  8,   0, 101])

Finally, use vector operations to calculate the difference between beer receipts and liquor receipts each month.

In [28]:
difference_of_beer_and_liquor = None
difference_of_beer_and_liquor
# array([   8,    0,   -9,   47,   58,   14,   -5,  156,   74,   29,    4,
#         211,  310, -105,  -16,   37,  317,  164,   15, -418, -268,  270,
#        -221,   15,   19, -345, -151, -253,   90,  -59,    0,   34,  242,
#          61,   34,  284,  -13,   42,  300, -189,   81,  293,  -37,  133,
#          26,  238,  118, -225,  233,   39,   21,  -33,  209,  109, -164,
#        -253,   21,    4,   91,   66,  166,   80,   19,  -54,  242,  -62,
#         170,  263,  -83,  197, -175,   -3, -439,   10,  -16,  182,   50,
#         134,  -47,  -31,  -45,  271,   67, -354, -100,    0,  251,  -97,
#         -92,  -10, -343,   32,   38,  260,  305,  265,  -42,  -22,   35,
#         -46,   43,    0,  275,    0, -126,  -47,  341,   22,   33,   29,
#           0,   84,  101,  243, -280])

array([   8,    0,   -9,   47,   58,   14,   -5,  156,   74,   29,    4,
        211,  310, -105,  -16,   37,  317,  164,   15, -418, -268,  270,
       -221,   15,   19, -345, -151, -253,   90,  -59,    0,   34,  242,
         61,   34,  284,  -13,   42,  300, -189,   81,  293,  -37,  133,
         26,  238,  118, -225,  233,   39,   21,  -33,  209,  109, -164,
       -253,   21,    4,   91,   66,  166,   80,   19,  -54,  242,  -62,
        170,  263,  -83,  197, -175,   -3, -439,   10,  -16,  182,   50,
        134,  -47,  -31,  -45,  271,   67, -354, -100,    0,  251,  -97,
        -92,  -10, -343,   32,   38,  260,  305,  265,  -42,  -22,   35,
        -46,   43,    0,  275,    0, -126,  -47,  341,   22,   33,   29,
          0,   84,  101,  243, -280])

Now let's imagine that the tax is .1 of all of the beer receipts and .2 of all of the liquor receipts.  Calculate the total tax for each month.

In [29]:


# array([  0.8,   0. ,  15.6,  20.3,  21.4,  18.5,  39.4,  23.4,  19.4,
#         34.1,  43.6, 119.2, 133. , 135.3, 113.3,  38.5,  85.7,  59.6,
#         53.1, 238.7, 171.8,  82.5, 158.5,  45.6,  25.3, 201.6, 152.9,
#        179.3,  57.3,  39.4,   0. ,  21.1, 110.6,  50.2,  24.1, 110.9,
#         38.3,  39. , 124.5, 140.4,  24.3,  99.5,  96.5,  36.7,  50.9,
#         68.5,  34.6, 222. , 113.9,  26.7, 109.2,  33. ,  76.4,  39.4,
#         82.3, 164. ,  43.8,  61.6, 104.8,  60. ,  59.8,  31.4,  40.3,
#         49.5, 126.8,  68.5,  67.1, 180.5,  96.4, 115.4,  96.5,  48.6,
#        237.2,  36.4,  73.7,  93.8,  55.4,  70.1, 128.8,  80.9,  67.8,
#         83.8,  29.2, 192.9, 174.5,   0. ,  33.2, 134.9, 137.2,  46.7,
#        162.5,  36.5,  26.6, 100.4,  80.6,  50.8,  96. ,  38.9,  37.7,
#         84.5,  68.2,  52.5, 103.1,   0. , 131.4,  35.2, 124.7,  46.9,
#         33.9, 125.6,  55.5,  17.7,  59.9, 102.6, 150.5])

array([  0.8,   0. ,  15.6,  20.3,  21.4,  18.5,  39.4,  23.4,  19.4,
        34.1,  43.6, 119.2, 133. , 135.3, 113.3,  38.5,  85.7,  59.6,
        53.1, 238.7, 171.8,  82.5, 158.5,  45.6,  25.3, 201.6, 152.9,
       179.3,  57.3,  39.4,   0. ,  21.1, 110.6,  50.2,  24.1, 110.9,
        38.3,  39. , 124.5, 140.4,  24.3,  99.5,  96.5,  36.7,  50.9,
        68.5,  34.6, 222. , 113.9,  26.7, 109.2,  33. ,  76.4,  39.4,
        82.3, 164. ,  43.8,  61.6, 104.8,  60. ,  59.8,  31.4,  40.3,
        49.5, 126.8,  68.5,  67.1, 180.5,  96.4, 115.4,  96.5,  48.6,
       237.2,  36.4,  73.7,  93.8,  55.4,  70.1, 128.8,  80.9,  67.8,
        83.8,  29.2, 192.9, 174.5,   0. ,  33.2, 134.9, 137.2,  46.7,
       162.5,  36.5,  26.6, 100.4,  80.6,  50.8,  96. ,  38.9,  37.7,
        84.5,  68.2,  52.5, 103.1,   0. , 131.4,  35.2, 124.7,  46.9,
        33.9, 125.6,  55.5,  17.7,  59.9, 102.6, 150.5])

### Summary

Great job!  In this lesson we practiced selecting entries from vectors, and adding vectors.

### Resources

* Original API
`'https://data.texas.gov/resource/naix-2893.json?location_address=2411%20GLENNA%20GOODACRE%20BLVD'`