# Matrix Matrix Multiplication

### Introduction

Now that we've learned how to multiply a vector by a matrix, it's time to learn about what's involved in multiplying a matrix by a matrix.  We'll also see how this compares to the matrix vector multiplication that we learned previously.

### Review Matrix Vector Multiplication

So far we have seen one way to multiply a matrix by a vector.  Multiply each entry in the vector by the respective column in the matrix.  Then add the two columns.  

$A \cdot x =  \begin{pmatrix}
    200 & 800 \\
    500 & 600\\
    1000 & 700\\
    2000 & 300\\
    3000 & 100\\
\end{pmatrix} \cdot \begin{pmatrix}
    .35 \\ .6 
\end{pmatrix} = .35* \begin{pmatrix}
    200  \\
    500  \\
    1000 \\
    2000 \\ 
    3000 \\ 
\end{pmatrix} + .6* \begin{pmatrix}
     800 \\
     600 \\
     700 \\
     300 \\ 
     100 \\ 
\end{pmatrix}  = \begin{pmatrix}
     70 \\
     175 \\
     350 \\
     700 \\ 
     1050 \\ 
\end{pmatrix} +  \begin{pmatrix}
     480 \\
     360 \\
     420 \\
     180 \\ 
     60 \\ 
\end{pmatrix} = 
\begin{pmatrix}
     550 \\
     535 \\
     770 \\
     880 \\ 
     1010 \\ 
\end{pmatrix}
$

In [3]:
import numpy as np
A = np.array([
    [200, 800],
    [500, 600],
    [1000, 700],
    [2000, 300],
    [3000, 100]])

x = np.array([.35, .6])

In [4]:
A.dot(x)

array([ 550.,  535.,  770.,  880., 1110.])

A second way to perform matrix vector multiplication is to multiply each row by each column.  The resulting vector is thus each row dotted with the vector $x$.

$$A \cdot x =  \begin{pmatrix}
    [\leftarrow a_1 \rightarrow] \\
    [\leftarrow a_2 \rightarrow] \\
    [\leftarrow a_3 \rightarrow]\\
    [\leftarrow a_4 \rightarrow]\\
    [\leftarrow a_5 \rightarrow]\\
\end{pmatrix} \cdot \begin{pmatrix}
    \uparrow \\ x \\ \downarrow \end{pmatrix} =  \begin{pmatrix} a_1 \cdot x \\ a_2 \cdot x \\ a_3 \cdot x \\ a_4 \cdot x \\ a_5 \cdot x  \end{pmatrix}$$

In [10]:
A[0, :].dot(x)

550.0

In [11]:
A[1, :].dot(x), A[2, :].dot(x), A[3, :].dot(x), A[4, :].dot(x)

(535.0, 770.0, 880.0, 1110.0)

As we'll see we can perform similar procedures in matrix matrix multiplication.

### Matrix Matrix Multiplication

We just saw that we can perform matrix vector multiplication by taking each row and the corresponding column to produce the corresponding entry in the resulting vector.

$$A \cdot x =  \begin{pmatrix}
    [\leftarrow a_1 \rightarrow] \\
    [\leftarrow a_2 \rightarrow] \\
    [\leftarrow a_3 \rightarrow]\\
    [\leftarrow a_4 \rightarrow]\\
    [\leftarrow a_5 \rightarrow]\\
\end{pmatrix} \cdot \begin{pmatrix}
    \uparrow \\ x \\ \downarrow \end{pmatrix} =  \begin{pmatrix} a_1 \cdot x \\ a_2 \cdot x \\ a_3 \cdot x \\ a_4 \cdot x \\ a_5 \cdot x  \end{pmatrix}$$

With matrix matrix multiplication, we can also think of this as a series of dot products.

$$A \cdot x =  \begin{pmatrix}
    [\leftarrow a_1 \rightarrow] \\
    [\leftarrow a_2 \rightarrow] \\
    [\leftarrow a_3 \rightarrow]\\
    [\leftarrow a_4 \rightarrow]\\
    [\leftarrow a_5 \rightarrow]\\
\end{pmatrix} \cdot \begin{pmatrix}
    \uparrow & \uparrow  \\ x_1 & x_2 \\ \downarrow  & \downarrow \end{pmatrix} =  \begin{pmatrix} a_1 \cdot x_1 & a_1 \cdot x_2 \\ a_2 \cdot x_1 & a_2 \cdot x_2 \\ a_3 \cdot x_1 & a_3 \cdot x_2 \\ a_4 \cdot x_1 & a_4 \cdot x_2 \\ a_5 \cdot x_1 & a_5 \cdot x_2  \end{pmatrix}$$

So looking at the above, we can see that, letting $A \cdot x = B$, that in the resulting matrix $B$, the entries:
* the $B_{11} = a_1 \cdot x_1$,
* and $B_{52} = a_5 \cdot x_2$.

Now let's see an example of the above.  We'll declare to matrices, A and X multiplying them together get the following:

In [14]:
import numpy as np
A = np.array([
    [200, 800],
    [500, 600],
    [1000, 700],
    [2000, 300],
    [3000, 100]])

X = np.array([[1, 2], 
              [3, 4]])

In [15]:
A.dot(x)

array([[2600, 3600],
       [2300, 3400],
       [3100, 4800],
       [2900, 5200],
       [3300, 6400]])

Breaking down the first entry in the resulting vector it should be the first row of $A$ dotted with the first column of $X$.

In [16]:
A[0, :].dot(X[:, 0])

2600

### Implications of the Above

Let's take note of a couple of items from the above.

1. Multiplication is not commutative 

In the above, with matrix multiplication it is always *rows of the first* matrix dotted with *columns of the second* matrix.  This means that $A \cdot X \neq X \cdot A $.

In [18]:
A.dot(X)

array([[2600, 3600],
       [2300, 3400],
       [3100, 4800],
       [2900, 5200],
       [3300, 6400]])

Notice that in our example above, $X \cdot A$ doesn't even work.

In [19]:
X.dot(A)

ValueError: shapes (2,2) and (5,2) not aligned: 2 (dim 1) != 5 (dim 0)

2. Matrix Dimensions

For matrix-matrix multiplication to work, for us to be able to dot a row with a column, the length of the rows in the first matrix must equal the length of the columns in the second matrix.  Let's see this.

In [20]:
A

array([[ 200,  800],
       [ 500,  600],
       [1000,  700],
       [2000,  300],
       [3000,  100]])

In [21]:
X

array([[1, 2],
       [3, 4]])

So we can see that if we multiply $A \cdot X$, that the rows of the first and the columns of the second are both 2.  However, in $X \cdot A$, the length of the rows are 2 while the length of the columns are 5.  Let's look at the error message again.

In [22]:
X.dot(A)

ValueError: shapes (2,2) and (5,2) not aligned: 2 (dim 1) != 5 (dim 0)

We can see that it is telling us there is a mismatch.

A nice way to check if matrix matrix multiplication can be performed is by looking at the shapes of the matrix.  So for example, we can write our two attempts at multiplication above as:  

1. $A_{5 x 2} \cdot X_{2 x 2}$
2. $  X_{2 x 2} \cdot A_{5 x 2}$

Now writing it as the above, we can check if the operation will compile by checking that the inner numbers are equal.  For the operation to work, the inner two numbers must be equal.  So we can see in the first multiplication that this will work as $2 == 2$.  But the second operation does not work, as $2 \neq 5 $.

In [24]:
X.dot(A)

ValueError: shapes (2,2) and (5,2) not aligned: 2 (dim 1) != 5 (dim 0)

The second thing we can see from the above is the shape of the resulting matrix.  The rule is that the resulting matrix is the shape of the outer two dimensions.  So our first multiplication $A_{5 x 2} \cdot X_{2 x 2} = B_{5x2}$.

In [27]:
A.dot(X)

array([[2600, 3600],
       [2300, 3400],
       [3100, 4800],
       [2900, 5200],
       [3300, 6400]])

### Summary

In this lesson, we learned about matrix matrix multiplication.  We saw that we can perform matrix-matrix multiplication by multiplying the rows of the first matrix by the columns of the second matrix.

$$A \cdot x =  \begin{pmatrix}
    [\leftarrow a_1 \rightarrow] \\
    [\leftarrow a_2 \rightarrow] \\
    [\leftarrow a_3 \rightarrow]\\
    [\leftarrow a_4 \rightarrow]\\
    [\leftarrow a_5 \rightarrow]\\
\end{pmatrix} \cdot \begin{pmatrix}
    \uparrow & \uparrow  \\ x_1 & x_2 \\ \downarrow  & \downarrow \end{pmatrix} =  \begin{pmatrix} a_1 \cdot x_1 & a_1 \cdot x_2 \\ a_2 \cdot x_1 & a_2 \cdot x_2 \\ a_3 \cdot x_1 & a_3 \cdot x_2 \\ a_4 \cdot x_1 & a_4 \cdot x_2 \\ a_5 \cdot x_1 & a_5 \cdot x_2  \end{pmatrix}$$

We also saw implications of this.  The first implication is that $A \cdot X \neq X \cdot A$.  The second is that the dimensions of our two matrices are important.  We can denote the dimensions of our matrices with something like the following:

$A_{5 x 2} \cdot X_{2 x 2}$

The inner two dimensions must be equal for matrix matrix multiplication to work.  And the resulting matrix will be of the shape of the outer two dimensions.  So in the example above the resulting matrix B will be $B_{5x2}$.