# Matrix Matrix Multiplication

### Introduction

Now that we've learned how to multiply a *vector* by a matrix, it's time to learn about what's involved in multiplying a matrix by a matrix.  We'll also see how this compares to the matrix vector multiplication that we learned previously.

### Review Matrix Vector Multiplication

We have seen that one way to multiply a matrix $A$ by a vector $x$ is to dot each row of the matrix $A$ with the vector $x$.  

$$A \cdot x =  \begin{pmatrix}
    [\leftarrow a_1 \rightarrow] \\
    [\leftarrow a_2 \rightarrow] \\
    [\leftarrow a_3 \rightarrow]\\
    [\leftarrow a_4 \rightarrow]\\
    [\leftarrow a_5 \rightarrow]\\
\end{pmatrix} \cdot \begin{pmatrix}
    \uparrow \\ x \\ \downarrow \end{pmatrix} =  \begin{pmatrix} a_1 \cdot x \\ a_2 \cdot x \\ a_3 \cdot x \\ a_4 \cdot x \\ a_5 \cdot x  \end{pmatrix}$$

In [2]:
import numpy as np
A = np.array([
    [200, 800],
    [500, 600],
    [1000, 700],
    [2000, 300],
    [3000, 100]])

x = np.array([.35, .6])

In [3]:
A.dot(x)

array([ 550.,  535.,  770.,  880., 1110.])

In [7]:
A[0, :].dot(x), A[1, :].dot(x), A[2, :].dot(x), A[3, :].dot(x), A[4, :].dot(x)

(550.0, 535.0, 770.0, 880.0, 1110.0)

As we'll see we can perform similar procedures in matrix matrix multiplication.

### Matrix Matrix Multiplication

As mentioned above, we can perform matrix vector multiplication by taking each row and the corresponding column to produce the corresponding entry in the resulting vector.

$$A \cdot x =  \begin{pmatrix}
    [\leftarrow a_1 \rightarrow] \\
    [\leftarrow a_2 \rightarrow] \\
    [\leftarrow a_3 \rightarrow]\\
    [\leftarrow a_4 \rightarrow]\\
    [\leftarrow a_5 \rightarrow]\\
\end{pmatrix} \cdot \begin{pmatrix}
    \uparrow \\ x \\ \downarrow \end{pmatrix} =  \begin{pmatrix} a_1 \cdot x \\ a_2 \cdot x \\ a_3 \cdot x \\ a_4 \cdot x \\ a_5 \cdot x  \end{pmatrix}$$

With matrix matrix multiplication, we can also think of this as a series of dot products.  Let's have $X$ now be a two column matrix.  Take a look at what it means to multiply $A \cdot X$.

$$A \cdot X =  \begin{pmatrix}
    [\leftarrow a_1 \rightarrow] \\
    [\leftarrow a_2 \rightarrow] \\
    [\leftarrow a_3 \rightarrow]\\
    [\leftarrow a_4 \rightarrow]\\
    [\leftarrow a_5 \rightarrow]\\
\end{pmatrix} \cdot \begin{pmatrix}
    \uparrow & \uparrow  \\ x_1 & x_2 \\ \downarrow  & \downarrow \end{pmatrix} =  \begin{pmatrix} a_1 \cdot x_1 & a_1 \cdot x_2 \\ a_2 \cdot x_1 & a_2 \cdot x_2 \\ a_3 \cdot x_1 & a_3 \cdot x_2 \\ a_4 \cdot x_1 & a_4 \cdot x_2 \\ a_5 \cdot x_1 & a_5 \cdot x_2  \end{pmatrix}$$

So looking at the above, we can see that, in the resulting matrix $B$, the entries:
* the $B_{11} = a_1 \cdot x_1$,
* and $B_{52} = a_5 \cdot x_2$.

> So we get each entry by looking to the corresponding row vector $A$ and column vector of $X$.

Now let's see this in code.  We'll declare to matrices, A and X multiplying them together get the following:

In [13]:
import numpy as np
A = np.array([
    [200, 800],
    [500, 600],
    [1000, 700],
    [2000, 300],
    [3000, 100]])

X = np.array([[1, 2], 
              [3, 4]])

In [14]:
A.dot(X)

array([[2600, 3600],
       [2300, 3400],
       [3100, 4800],
       [2900, 5200],
       [3300, 6400]])

Breaking down the first entry in the resulting matrix B_11, it should come from the first row of $A$ dotted with the first column of $X$.

In [15]:
A[0, :].dot(X[:, 0])

2600

### Implications of the Above

Let's take note of a couple of items that follow from the above.

1. Multiplication is not commutative 

In the above, with matrix multiplication it is always *rows of the first* matrix dotted with *columns of the second* matrix.  This means that $A \cdot X \neq X \cdot A $.

In [11]:
A.dot(X)

array([[2600, 3600],
       [2300, 3400],
       [3100, 4800],
       [2900, 5200],
       [3300, 6400]])

Notice that in our example above, $X \cdot A$ doesn't even work.

In [12]:
X.dot(A)

ValueError: shapes (2,2) and (5,2) not aligned: 2 (dim 1) != 5 (dim 0)

2. Matrix Dimensions

For matrix-matrix multiplication to work, that is, for us to be able to dot the row of A with the column of X, the length of a row in A must equal the length of a column in X.  Let's see this.

In [20]:
A

array([[ 200,  800],
       [ 500,  600],
       [1000,  700],
       [2000,  300],
       [3000,  100]])

In [21]:
X

array([[1, 2],
       [3, 4]])

So we can see that if we multiply $A \cdot X$, that the rows of the first and the columns of the second are both 2.  So, to multiply the two together, we dot a row of $A$ with a column in $X$.

However, in $X \cdot A$, the length of a row in the first matrix is 2 while the length of the a column of the second is 5.  Let's look at the error message again.

In [22]:
X.dot(A)

ValueError: shapes (2,2) and (5,2) not aligned: 2 (dim 1) != 5 (dim 0)

We can see that it is telling us there is a mismatch.

A nice way to check if matrix matrix multiplication can be performed is by looking at the shapes of the matrix.  So for example, we can write our two attempts at multiplication above as:  

1. $A_{5 x 2} \cdot X_{2 x 2}$
2. $  X_{2 x 2} \cdot A_{5 x 2}$

Now writing it as the above, we can check if the operation will compile by checking that the inner numbers are equal.  For the operation to work, the inner two numbers must be equal.  So we can see in the first multiplication that this will work as $2 == 2$.  But the second operation does not work, as $2 \neq 5 $.

In [24]:
X.dot(A)

ValueError: shapes (2,2) and (5,2) not aligned: 2 (dim 1) != 5 (dim 0)

The second thing we can see from the above is the shape of the *resulting* matrix.  The resulting matrix is always the shape of the outer two dimensions.  So with our  multiplication of $A_{5 x 2} \cdot X_{2 x 2}$ we get  $B_{5x2}$.

In [27]:
A.dot(X)

array([[2600, 3600],
       [2300, 3400],
       [3100, 4800],
       [2900, 5200],
       [3300, 6400]])

In [16]:
A.shape, X.shape, A.dot(X).shape

((5, 2), (2, 2), (5, 2))

### Summary

In this lesson, we learned about matrix matrix multiplication.  We saw that we can perform matrix-matrix multiplication by multiplying the rows of the first matrix by the columns of the second matrix.

$$A \cdot x =  \begin{pmatrix}
    [\leftarrow a_1 \rightarrow] \\
    [\leftarrow a_2 \rightarrow] \\
    [\leftarrow a_3 \rightarrow]\\
    [\leftarrow a_4 \rightarrow]\\
    [\leftarrow a_5 \rightarrow]\\
\end{pmatrix} \cdot \begin{pmatrix}
    \uparrow & \uparrow  \\ x_1 & x_2 \\ \downarrow  & \downarrow \end{pmatrix} =  \begin{pmatrix} a_1 \cdot x_1 & a_1 \cdot x_2 \\ a_2 \cdot x_1 & a_2 \cdot x_2 \\ a_3 \cdot x_1 & a_3 \cdot x_2 \\ a_4 \cdot x_1 & a_4 \cdot x_2 \\ a_5 \cdot x_1 & a_5 \cdot x_2  \end{pmatrix}$$

We also saw implications of this.  The first implication is that $A \cdot X \neq X \cdot A$.  The second is that the dimensions of our two matrices are important.  We can denote the dimensions of our matrices with something like the following:

$A_{5 x 2} \cdot X_{2 x 2}$

The inner two dimensions must be equal for matrix matrix multiplication to work.  And the resulting matrix will be of the shape of the outer two dimensions.  So in the example above the resulting matrix B will be $B_{5x2}$.