* Because linearly independent, means that in each direction.

### Singular Values and Vectors

$A^TA $: Symmetric, square, have positive eigenvalues with same rank as A.

* Eigenvectors for $AA^T$ is $u_i$, and $A^TA$ is $v_i$.  And square roots of the eigenvalues are singular values.

* These are orthonormal.

### SVD 

* Any matrix A can be factorized as $A = USV^T$.

* S is the eigenvalues, so it tells us how much in each direction we should stretch.

<img src="https://miro.medium.com/max/1400/1*tmVzY_1k9_JpxyKDkXwAQA.jpeg">

<img src="https://miro.medium.com/max/1400/1*n5pHiLBbkM2kza1OFUsLNg.jpeg">

* And we order the eigenvectors such that the vectors with higher eigenvalues, come before those with smaller values.

> So this means that these are the more significant components.

* Moving to an example

In [2]:
import numpy as np
A = np.array([[3, 2, 2], 
              [2, 3, -2]
             ])

In [3]:
AAT = A.dot(A.T)

In [4]:
ATA = A.T.dot(A)

In [5]:
AAT

array([[17,  8],
       [ 8, 17]])

In [6]:
ATA

array([[13, 12,  2],
       [12, 13, -2],
       [ 2, -2,  8]])

In [7]:
U = np.array([[1/np.sqrt(2), 1/np.sqrt(2)], 
              [1/np.sqrt(2), - 1/np.sqrt(2)]])

In [8]:
V = np.array([[1/np.sqrt(2), 1/np.sqrt(18), 2/3], 
              [1/np.sqrt(2), - 1/np.sqrt(18), -2/3],
             [0, 4/np.sqrt(18), -1/3]])

In [9]:
S = np.array([[5, 0, 0], 
              [0, 3, 0]])

In [16]:
U[:, :1], V[:, :1].T

(array([[0.70710678],
        [0.70710678]]),
 array([[0.70710678, 0.70710678, 0.        ]]))

In [17]:
A

array([[ 3,  2,  2],
       [ 2,  3, -2]])

In [29]:
5*U[:, :1].dot(V[:, :1].T) + 3*U[:, 1:].dot(V[:, 1:2].T)

array([[ 3.,  2.,  2.],
       [ 2.,  3., -2.]])

In [25]:
V

array([[ 0.70710678,  0.23570226,  0.66666667],
       [ 0.70710678, -0.23570226, -0.66666667],
       [ 0.        ,  0.94280904, -0.33333333]])

In [28]:
3*U[:, 1:].dot(V[:, 1:2].T)

array([[ 0.16666667, -0.16666667,  0.66666667],
       [-0.16666667,  0.16666667, -0.66666667]])

In [ ]:
# 3*U[:, 1:].dot(V[:, 1:2].T)

### Moore Penrose Pseudo Inverse