# Unpacking SVD Lab

### Introduction

Let's use this lesson to continue our exploration of SVD.  We'll see that singular value decomposition consists of breaking any matrix A down into the multiplication of $U \Sigma V $, where both U and V are orthonormal matrices and $\Sigma$ is a diagonal matrix consisting of the singular values.

### Initializing our Data

Let's begin by initializing our matrix $A$.

In [4]:
import numpy as np
A = np.array([[5, 2, 9], 
              [1, 3, -2],
              [4, 7, 3]
             ])

Now as we know, we can think of any matrix as rotating, stretching, and transforming space.  Let's use singular value decomposition to break this into three matrices that perform rotating, stretching, and rotating again separately.

> Use SVD to decompose the matrix A into three separate matrices below.

In [95]:
from numpy.linalg import svd

U, S, V = svd(A)

In [96]:
U, S, V

# (array([[-0.79645143, -0.51550667,  0.31609806],
#         [-0.04150516,  0.56810322,  0.82191   ],
#         [-0.60327642,  0.6414917 , -0.47386282]]),
#  array([12.4835888 ,  6.46578463,  0.59467619]),
#  array([[-0.5156264 , -0.47585301, -0.71252602],
#         [ 0.08607411,  0.79862515, -0.59564177],
#         [ 0.85247913, -0.36845867, -0.37083359]]))

(array([[-0.79645143, -0.51550667,  0.31609806],
        [-0.04150516,  0.56810322,  0.82191   ],
        [-0.60327642,  0.6414917 , -0.47386282]]),
 array([12.4835888 ,  6.46578463,  0.59467619]),
 array([[-0.5156264 , -0.47585301, -0.71252602],
        [ 0.08607411,  0.79862515, -0.59564177],
        [ 0.85247913, -0.36845867, -0.37083359]]))

Now use matrix multiplication to recreate our original matrix $A$.

> To do so, we'll need to turn the singular values in S into a diagonal matrix.

In [7]:
from numpy import diag
diag_S = diag(S)

Ok, now let's multiply recreate our original matrix.

In [97]:
U.dot(diag_S).dot(V)

# array([[ 5,  2,  9],
#        [ 1,  3, -2],
#        [ 4,  7,  3]])

array([[ 5.,  2.,  9.],
       [ 1.,  3., -2.],
       [ 4.,  7.,  3.]])

### Freeze Frame

Now as we know, SVD uses the three matrices to separate the steps of a rotation, a stretch, and another rotation.  Let's see this visually.  We'll do so, by plotting the impact that a matrix $A$ has on a vector $X$, and then we'll see how our three matrices $USV^T $ perform the same operation as $A$.

> We'll start by loading up our `vector_trace` function.

In [25]:
def vector_trace(vector, name = '', text = ''):
    return {'x': [0, vector[0]], 'y': [0, vector[1]], 
             'mode': 'lines+markers', 'name': name, 'text': text}

And initializing a vector $b$.

In [19]:
b = np.array([4, 5, 6])

Now let's calculate $b \cdot A$.

In [43]:
b_dot_A = (b).dot(A)
b_dot_A

# array([49, 65, 44])

array([49, 65, 44])

Now let's plot our vector `b` and the resulting vector `b_dot_A`.

In [29]:
import plotly.graph_objects as go
b_trace = vector_trace(b, name = 'b')
b_dot_A_trace = vector_trace(A_dot_b, name = 'A dot b')
layout = go.Layout(yaxis=dict(scaleanchor="x", scaleratio=1))
go.Figure(data = [b_trace, b_dot_A_trace], layout = layout)

Now let's see this impact sequentially.  Let's calculate $b \cdot USV$ in steps.

$A\cdot b = b \cdot USV^T$

First calculate $b \cdot U$ to calculate the effect of a rotation.

In [52]:
rotate = b.dot(U)
rotate
# array([-7.01299005,  4.62743961,  2.53076534])

array([-7.01299005,  4.62743961,  2.53076534])

Then let's perform the stretch of our rotation vector.

In [53]:
stretch = rotate.dot(diag_S)
stretch
# array([-87.54728408,  29.92002788,   1.50498588])

array([-87.54728408,  29.92002788,   1.50498588])

Finally, let's do the final rotation.

In [54]:
final_rotation = stretch.dot(V)
final_rotation

# array([49., 65., 44.])

array([49., 65., 44.])

Ok, now we'll plot the graph below.

In [55]:
import plotly.graph_objects as go
rotate_trace = vector_trace(rotate, name = 'rotate trace')
stretch_trace = vector_trace(stretch, name = 'stretch trace')
final_rotation_trace = vector_trace(final_rotation, name = 'final rotation')
go.Figure(data = [b_trace, rotate_trace, stretch_trace, final_rotation_trace])

So we can see that these three matrices do in fact perform the steps to rotate, and stretch, and then rotate our vector $b$ again.  Matrix decomposition has been achieved!

### Why it matters

The reason why this is useful is because our whole goal with principal component analysis is to break down our matrix, and somehow retain the components that are useful.  To somehow much of the data in the matrix.  Let's take a look at the three matrices provided by SVD again.

In [56]:
U, diag_S, V

(array([[-0.79645143, -0.51550667,  0.31609806],
        [-0.04150516,  0.56810322,  0.82191   ],
        [-0.60327642,  0.6414917 , -0.47386282]]),
 array([[12.4835888 ,  0.        ,  0.        ],
        [ 0.        ,  6.46578463,  0.        ],
        [ 0.        ,  0.        ,  0.59467619]]),
 array([[-0.5156264 , -0.47585301, -0.71252602],
        [ 0.08607411,  0.79862515, -0.59564177],
        [ 0.85247913, -0.36845867, -0.37083359]]))

As we know, with the diagonal matrix $\Sigma$, our the values are ordered from largest to smallest.  Now let's think about what it means to multiply these three matrices together.  We can rewrite $USV^T$ as the following: 

$A = U \Sigma V^T $

> Remember that this is a series of row by column multiplications.  Perform the three multiplications below.  Assign each to a separate matrix.

In [99]:
U, diag_S, V

(array([[-0.79645143, -0.51550667,  0.31609806],
        [-0.04150516,  0.56810322,  0.82191   ],
        [-0.60327642,  0.6414917 , -0.47386282]]),
 array([[12.4835888 ,  0.        ,  0.        ],
        [ 0.        ,  6.46578463,  0.        ],
        [ 0.        ,  0.        ,  0.59467619]]),
 array([[-0.5156264 , -0.47585301, -0.71252602],
        [ 0.08607411,  0.79862515, -0.59564177],
        [ 0.85247913, -0.36845867, -0.37083359]]))

In [112]:
s1 = 12.4835
s2 = 6.46
s3 = 0.59467619

In [116]:
first_multiplication = s1*U[:, :1].dot(V[:1, :])
first_multiplication

array([[5.12661628, 4.73116923, 7.08429099],
       [0.26716136, 0.24655358, 0.36918089],
       [3.88318304, 3.58364955, 5.36603427]])

In [117]:
second_multiplication = s2*U[:, 1:2].dot(V[1:2, :])
second_multiplication

array([[-0.28664168, -2.65955999,  1.98359021],
       [ 0.3158874 ,  2.93091183, -2.18597364],
       [ 0.35669423,  3.30953165, -2.46836116]])

In [118]:
third_multiplication = s3*U[:, 2:3].dot(V[2:3, :])
third_multiplication

array([[ 0.16024561, -0.06926138, -0.06970781],
       [ 0.41666648, -0.18009166, -0.18125245],
       [-0.2402243 ,  0.10382979,  0.10449903]])

Then combine the three products to return to the original matrix.

In [119]:
first_multiplication + second_multiplication + third_multiplication

# array([[ 5.00022021,  2.00234785,  8.99817339],
#        [ 0.99971524,  2.99737375, -1.99804519],
#        [ 3.99965297,  6.99701098,  3.00217213]])

array([[ 5.00022021,  2.00234785,  8.99817339],
       [ 0.99971524,  2.99737375, -1.99804519],
       [ 3.99965297,  6.99701098,  3.00217213]])

In [120]:
A

array([[ 5,  2,  9],
       [ 1,  3, -2],
       [ 4,  7,  3]])

Now as we know, we have the effect of rebuilding our original matrix in layers.  Calculate the percentage of the information in the matrix we will retain if we only include the first two columns from each matrix instead of three.

In [123]:
S[:2].sum()/S.sum()

# 0.9695725195807149

0.9695725195807149

So we can see that we retain .96 of the original matrix.  Next let's perform matrix matrix multiplication to reduce each matrix by a single column.

In [127]:
U[:, :2].dot(diag_S[:2, :2]).dot(V[:2, :3])

# array([[ 4.83975439,  2.06926138,  9.06970781],
#        [ 0.58333352,  3.18009165, -1.81874755],
#        [ 4.2402243 ,  6.89617021,  2.89550097]])

array([[ 4.83975439,  2.06926138,  9.06970781],
       [ 0.58333352,  3.18009165, -1.81874755],
       [ 4.2402243 ,  6.89617021,  2.89550097]])

Let's compare this with our original matrix $A$.

In [128]:
A

array([[ 5,  2,  9],
       [ 1,  3, -2],
       [ 4,  7,  3]])

### Summary

In this lab, we further explored PCA.  We saw through various different plots how SVD breaks down the operations of a matrix A into three separate matrices that rotate, stretch, and rotate space again: $U\Sigma V^T$.  

We also saw how we can use SVD to rebuild our matrix A in layers.  In doing so, we can ultimately reduce the dimensions of our $U\Sigma V^T$ matrices.  While some information is lost in the process, it may be worth the tradeoff of reducing the dimensions of our data.  

### SVD 

[PCA vs SVD](https://intoli.com/blog/pca-and-svd/)